/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import org.graphstream.graph.implementations.MultiGraph;

/**
 *
 * @author Satrio
 */
public class Main extends javax.swing.JFrame{

    /**
     * Creates new form Main
     */
    
    // Variable
    MultiGraph g;
    public Main() {
        initComponents();
        g = new MultiGraph("test");
        txtPresent.setText("");
        txtInputQuery.setText("");
    }


    public MultiGraph getG() {
        return g;
    }

    public JButton getBtnDiameter() {
        return btnDiameter;
    }
    
    public JTextArea getTxtPresent() {
        return txtPresent;
    }

    public JButton getBtnViewEdge() {
        return btnViewEdge;
    }

    public JButton getBtnAddNode() {
        return btnAddNode;
    }

    public JButton getBtnAddEdge() {
        return btnAddEdge;
    }

    public JButton getBtnAddAttribute() {
        return btnAddAttribute;
    }

    public JButton getBtnDeleteNode() {
        return btnDeleteNode;
    }

    public JButton getBtnDeleteEdge() {
        return btnDeleteEdge;
    }

    public JButton getBtnDeleteAttribute() {
        return btnDeleteAttribute;
    }

    public JButton getBtnDisplayGraph() {
        return btnDisplayGraph;
    }

    public JButton getBtnViewNode() {
        return btnViewNode;
    }

    public JButton getBtnBetweeness() {
        return btnBetweeness;
    }

    public JPanel getPaneUtama() {
        return PaneUtama;
    }    

    public JButton getBtnCloseness() {
        return btnCloseness;
    }

    public JButton getBtnColoringNode() {
        return btnColoringNode;
    }

    public JToggleButton getBtnLoadGraph() {
        return btnLoadGraph;
    }

    public JMenuItem getMenuLoad() {
        return menuLoad;
    }

    public JFileChooser getChooser() {
        return chooser;
    }

    public JMenuItem getMenuSave() {
        return menuSave;
    }

    public JMenuItem getMenuExit() {
        return menuExit;
    }

    public JButton getBtnCluster() {
        return btnCluster;
    }

    public JButton getBtnExecute() {
        return btnExecute;
    }

    public JTextArea getTxtInputQuery() {
        return txtInputQuery;
    }
    
    public void addListener(ActionListener a){
        btnAddNode.addActionListener(a);
        btnAddEdge.addActionListener(a);
        btnAddAttribute.addActionListener(a);
        btnDeleteNode.addActionListener(a);
        btnDeleteEdge.addActionListener(a);
        btnDeleteAttribute.addActionListener(a);
        btnDisplayGraph.addActionListener(a);
        btnViewNode.addActionListener(a);
        btnViewEdge.addActionListener(a);
        btnDiameter.addActionListener(a);
        btnBetweeness.addActionListener(a);
        btnCloseness.addActionListener(a);
        btnColoringNode.addActionListener(a);
        btnCluster.addActionListener(a);
        btnLoadGraph.addActionListener(a);
        menuLoad.addActionListener(a);
        menuSave.addActionListener(a);
        menuExit.addActionListener(a);
        btnExecute.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    @SuppressWarnings(value = "unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        btnLoadGraph = new javax.swing.JToggleButton();
        PaneMain = new javax.swing.JPanel();
        PaneTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        PaneUtama = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPresent = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInputQuery = new javax.swing.JTextArea();
        btnExecute = new javax.swing.JButton();
        PaneMenu = new javax.swing.JPanel();
        btnAddNode = new javax.swing.JButton();
        btnAddEdge = new javax.swing.JButton();
        btnDeleteNode = new javax.swing.JButton();
        btnAddAttribute = new javax.swing.JButton();
        btnDeleteEdge = new javax.swing.JButton();
        btnDeleteAttribute = new javax.swing.JButton();
        btnDisplayGraph = new javax.swing.JButton();
        btnViewNode = new javax.swing.JButton();
        btnViewEdge = new javax.swing.JButton();
        btnDiameter = new javax.swing.JButton();
        btnBetweeness = new javax.swing.JButton();
        btnCluster = new javax.swing.JButton();
        btnColoringNode = new javax.swing.JButton();
        btnCloseness = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLoad = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        btnLoadGraph.setText("Load Graph");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        PaneMain.setBackground(new java.awt.Color(0, 0, 0));

        PaneTitle.setBackground(new java.awt.Color(255, 255, 255));
        PaneTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Graph Processing");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PaneTitleLayout = new javax.swing.GroupLayout(PaneTitle);
        PaneTitle.setLayout(PaneTitleLayout);
        PaneTitleLayout.setHorizontalGroup(
            PaneTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneTitleLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );
        PaneTitleLayout.setVerticalGroup(
            PaneTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        PaneUtama.setBackground(new java.awt.Color(0, 0, 0));
        PaneUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        txtPresent.setEditable(false);
        txtPresent.setColumns(20);
        txtPresent.setRows(5);
        txtPresent.setToolTipText("Text Hasil");
        jScrollPane1.setViewportView(txtPresent);

        txtInputQuery.setColumns(20);
        txtInputQuery.setRows(5);
        txtInputQuery.setToolTipText("Input your query here !");
        jScrollPane2.setViewportView(txtInputQuery);

        btnExecute.setText("Execute");

        javax.swing.GroupLayout PaneUtamaLayout = new javax.swing.GroupLayout(PaneUtama);
        PaneUtama.setLayout(PaneUtamaLayout);
        PaneUtamaLayout.setHorizontalGroup(
            PaneUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneUtamaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExecute)))
                .addContainerGap())
        );
        PaneUtamaLayout.setVerticalGroup(
            PaneUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExecute)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PaneMenu.setBackground(new java.awt.Color(0, 0, 0));
        PaneMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        btnAddNode.setText("Add Node");

        btnAddEdge.setText("Add Edge");

        btnDeleteNode.setText("Delete Node");

        btnAddAttribute.setText("Add Attribute");

        btnDeleteEdge.setText("Delete Edge");

        btnDeleteAttribute.setText("Delete Attribute");

        btnDisplayGraph.setText("Display Graph");

        btnViewNode.setText("View Node");

        btnViewEdge.setText("View Edge");

        btnDiameter.setText("Diameter");

        btnBetweeness.setText("Betweeness");

        btnCluster.setText("Cluster Node");

        btnColoringNode.setText("Coloring Node");

        btnCloseness.setText("Closeness");

        javax.swing.GroupLayout PaneMenuLayout = new javax.swing.GroupLayout(PaneMenu);
        PaneMenu.setLayout(PaneMenuLayout);
        PaneMenuLayout.setHorizontalGroup(
            PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDisplayGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(btnBetweeness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddAttribute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddNode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteNode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnColoringNode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCloseness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteEdge, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnAddEdge, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnDeleteAttribute, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnViewEdge, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnDiameter, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnCluster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaneMenuLayout.setVerticalGroup(
            PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNode)
                    .addComponent(btnAddEdge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteNode)
                    .addComponent(btnDeleteEdge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAttribute)
                    .addComponent(btnDeleteAttribute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewEdge)
                    .addComponent(btnViewNode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiameter)
                    .addComponent(btnColoringNode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBetweeness)
                    .addComponent(btnCloseness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplayGraph)
                    .addComponent(btnCluster))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PaneMainLayout = new javax.swing.GroupLayout(PaneMain);
        PaneMain.setLayout(PaneMainLayout);
        PaneMainLayout.setHorizontalGroup(
            PaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneMainLayout.createSequentialGroup()
                        .addComponent(PaneUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(PaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PaneTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PaneMainLayout.setVerticalGroup(
            PaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PaneUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        menuLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        menuLoad.setText("Load Graph");
        jMenu1.add(menuLoad);

        menuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        menuSave.setText("Save Graph");
        jMenu1.add(menuSave);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneMain;
    private javax.swing.JPanel PaneMenu;
    private javax.swing.JPanel PaneTitle;
    private javax.swing.JPanel PaneUtama;
    private javax.swing.JButton btnAddAttribute;
    private javax.swing.JButton btnAddEdge;
    private javax.swing.JButton btnAddNode;
    private javax.swing.JButton btnBetweeness;
    private javax.swing.JButton btnCloseness;
    private javax.swing.JButton btnCluster;
    private javax.swing.JButton btnColoringNode;
    private javax.swing.JButton btnDeleteAttribute;
    private javax.swing.JButton btnDeleteEdge;
    private javax.swing.JButton btnDeleteNode;
    private javax.swing.JButton btnDiameter;
    private javax.swing.JButton btnDisplayGraph;
    private javax.swing.JButton btnExecute;
    private javax.swing.JToggleButton btnLoadGraph;
    private javax.swing.JButton btnViewEdge;
    private javax.swing.JButton btnViewNode;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JTextArea txtInputQuery;
    private javax.swing.JTextArea txtPresent;
    // End of variables declaration//GEN-END:variables

    

}
